- .gitignore
This PR adds the package-lock.json to the gitignore file
> Ignoring package-lock.json

- package-lock.json
- src/HttpServer.ts
- src/ServerConfigParams.ts
- Always log the 'Listening on port' log regardless of the log level
- Fix the log level configuration
- The integration tests are failing
> PP-271: Fix integration tests

- Dockerfile
- Readme.md
- docker-compose.yml
- Port the Docker Compose configuration to the master branch.
-   Make the system more reproducible
-  [PP327](https://rsklabs.atlassian.net/browse/PP-327)
> PP-327: Port docker compose configuration to master branch

- package-lock.json
- package.json
- server-config.json
- src/Conversions.ts
- src/RelayServer.ts
- src/definitions/token.type.ts
- test/unit/Conversions.spec.ts
- test/unit/RelayServer.test.ts
- Integration of price feeder for RBTC-RIF
- Needed for revenue sharing validation process
- [PR #288 (Implement a token-RBTC conversion)](https://rsklabs.atlassian.net/browse/PP-288)
- https://github.com/rsksmart/rif-relay-contracts/pull/53
- https://github.com/rsksmart/rif-relay-common/pull/31
- https://github.com/rsksmart/rif-relay-client/pull/31
> PP-288/rif-rbtc

- Dockerfile
- package-lock.json
- tsconfig.json
- Change the ts configuration to generate files keeping the same structure of the src folder.
- Change the dockerfile to copy the dist folder from the previous stage instead of using the local folder.
- Update the package-lock.json to version 2.
- The docker build was failing
> PP-327: Fix docker configuration

- package-lock.json
- package.json
- update rif-relay-client
- we made an hotfix on the rif-relay-client package
> PP-508(hotfix): update rif-relay-client

- package-lock.json
- package.json
- Method to get the feesReceiver and partners
- To get in programmatically from the dApp
- [Jira 504](https://rsklabs.atlassian.net/browse/PP-504)
- https://github.com/rsksmart/rif-relay-contracts/pull/91
- https://github.com/rsksmart/rif-relay-client/pull/47
- https://github.com/rsksmart/rif-relay-common/pull/43
> PP-504/remove-worker-configuration

- package-lock.json
- package.json
- update package.json version and rif-relay-contracts dependency
- to use the updated version of the contracts and to release a new version of the common
> PP-105: signature verification on createUserSmartWallet call

- package-lock.json
- package.json
- src/RelayServer.ts
- src/ServerConfigParams.ts
- test/unit/GasEstimator.spec.ts
- test/unit/RelayServer.test.ts
-   Added an expiration config parameter and a check for the request expiration timestamp.
-  https://rsklabs.atlassian.net/jira/software/projects/PP/boards/84/backlog?selectedIssue=PP-583
-   (optional: include links to other issues, PRs, tickets, etc)
> REL-004 Expiration mechanism

- .github/workflows/deploy.rwm.yml
- docker-compose-rwm.yml
- server-config.rwm.json
This PR adds the server configuration and to configure the server to automatically deploy in the public RIF-Wallet mainnet environment.
> Add server configuration and CD for RIF wallet mainnet environment

- .github/workflows/deploy.rwm.yml
Fix the CD workflow to use the right script for RIF Wallet Mainnet.
> PP-625: Modify workflow to run script for rifwallet mainnet env

- config/default.json
- package-lock.json
- package.json
- src/RegistrationManager.ts
- src/RelayServer.ts
- src/ServerConfigParams.ts
- src/TransactionManager.ts
- src/Utils.ts
- src/commands/Start.ts
- changes to support dApp refactoring
- required by dApp refactor
- [update rif-relay-sample-dapp](https://rsklabs.atlassian.net/browse/PP-357)
- https://github.com/rsksmart/rif-relay-client/pull/68
> PP-357/dapp-update

- package-lock.json
- package.json
- src/HttpServer.ts
- src/RelayServer.ts
- src/ServerConfigParams.ts
- src/definitions/index.ts
- src/index.ts
- Migrate utility files used by the server
- Necessary to integration test
- [PP-642](https://rsklabs.atlassian.net/browse/PP-642)
> PP-642/migrate-test-utils-server

- tsconfig.build.json
- restore tsconfig.build.json
-  it was erroneously removed
> PP-653: restore tsconfig build

- package-lock.json
- package.json
- Update rif-relay dependencies to use the v2.0.0-beta.0
- We were using alpha versions
> Fix: update relay dependencies

- .github/workflows/main.yml
-  Run unit test in the CI workflow
- Unit tests aren't run on CI
> CI: run unit tests

- Readme.md
- config/default.json5
- src/RelayServer.ts
- src/ServerConfigParams.ts
- src/relayServerUtils.ts
- test/unit/RelayServer.test.ts
- test/unit/ServerConfigParams.test.ts
- test/unit/relayServerUtils.test.ts
-   Modify the fee calculation process to add a configurable fixed fee denominated in USD.
-   Add flexibility to the fee calculation process.
-   [PP-322](https://rsklabs.atlassian.net/browse/PP-322)
> PP322: Set up a configurable fixed fee in USD

- src/RelayServer.ts
-  add verifier check when relaying a transaction
- it was erroneously removed on #86
> PP-744: add verifier validation

- src/ReplenishFunction.ts
Logs for grafana notifications & alerts
To know when the manager and worker balance is getting too low
> PP-683: notifier logs

- package-lock.json
- package.json
- Implement Coingecko client to retrieve RBTC price
- Coinbase client doesn't support RBTC any more
> PP-753: Implement coingecko pricer

- src/ServerConfigParams.ts
-   update the import path for the error messages
-   after build, the module cannot be found.
-   [PP-722](https://rsklabs.atlassian.net/browse/PP-722)
> PP-722/fix-server-config-import

- config/testnet.json5
-   Change the log level in testnet configuration
-   To show more detailed logs.
> fix: change log level in testnet

- config/qa.json5
-   disable sponsored transaction in the QA environment
-   to reproduce some specific scenarios in QA
> test(qa): disable sponsored transaction in the QA environment

- src/RelayServer.ts
- src/relayServerUtils.ts
- test/unit/relayServerUtils.test.ts
- Fix the time logged when the request expiration time is expired or about to expire.
- The minimum acceptable time is wrongly loggerd.
> PP-779: fix expiration time logged

- config/qa.json5
-   New collector contract deployment
-  New features implemented.
> chore: qa configuration

- .github/workflows/deploy.boltz.testnet.yml
- .github/workflows/deploy.qa.yml
- .github/workflows/deploy.rwm.yml
- .github/workflows/deploy.rwt.yml
- .github/workflows/deploy.testnet.yml
Missed permissions
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
> fix: add permissions to request oidc jwt id token

- package-lock.json
- package.json
- estimate the native payment using the feesReceiver
- using the tokenOrigin makes the estimation fail since the tokenOrigin doesn't have funds
> fix: client update

- config/boltz-testnet.json5
- package-lock.json
- package.json
- Boltz verifier validates claiming amount in native payment
- To avoid executing a relay tx that cannot cover the payment
- https://github.com/rsksmart/rif-relay-contracts/pull/165
- https://github.com/rsksmart/rif-relay-client/pull/95
> feat: boltz verifier claim amount

- package-lock.json
- package.json
-  Update package-lock
- To avoid using old versions of the relay packages
> Fix: update package lock

- config/boltz-testnet.json5
-   test boltz smart wallets
- 
-   new implementation
> build: boltz-testnet config

- package-lock.json
- package.json
- src/HttpServer.ts
- src/KeyManager.ts
- src/RelayServer.ts
- test/unit/RelayServer.test.ts
- Estimation without signature
- UX improvement to not require additional signed tx
- https://github.com/rsksmart/rif-relay-contracts/pull/168
- https://github.com/rsksmart/rif-relay-client/pull/96
> estimation-no-signature
