server-config.testnet.json

- Update the server URL on testnet
- We changed the server URL, so we need to re-register the server.
-  https://rsklabs.atlassian.net/browse/PP-96

PP-96/Update server URL on testnet

---

Readme.md

- Change the 'pre-requisites' section to include the RSKj node configuration required for Regtest.
- Many people struggled to start the server without knowing the exact RSKj configuration to use (e.g.: new joiners, QAs).

PP-138/Update Readme to include rskj configuration

---

Readme.md
scripts/register
scripts/start

Before this change, the only one source of configuration for the scripts start and register was server-config.json. After this change, it's possible to pass a different path as arguments. 
Because in networks different than regtest, the default configuration was failing.

Modify start and register to use a different configuration file

---

package.json

-   updates rif relay dependencies to versions that build upon install
-   to allow automatic build for development and production
- relates to https://rsklabs.atlassian.net/browse/PP-166
- source: https://www.npmjs.com/package/npmignore

fix(pub): uses relay deps that build on install

---

server-config.json
src/commands/Register.ts

Getting the loglevel form the config file. 
Although we’re using the loglevel library in the registration script, we aren’t setting the log level, so by default we cannot see what’s happening in the script. 
[PP-462](https://rsklabs.atlassian.net/browse/PP-462)

PP-462: Using loglevel from config file. 

---

src/RelayServer.ts
src/ServerConfigParams.ts
test/unit/RelayServer.test.ts

- Sponsor all
- Sponsor none
- Sponsor smart wallet creation, But not the transactions on the smart wallet
- Sponsor transactions for certain destination addresses (ex: sponsored deployment and also sponsored RNS request and RNS registration)
- More flexibility for the server
-   [PP-571](https://rsklabs.atlassian.net/browse/PP-571)

PP-571/flexible-sponsorship

---

.github/workflows/deploy.qa.yml
.github/workflows/deploy.rwt.yml
docker-compose-rwt.yml
server-config.rwt.json

Since we created a dedicated environment in TESTNET for the RIF Wallet, this is the CD to automatically deploy there. 
This CD associateS the deployment to a release creation having a specific tag format (e.g. vX.Y.Z-beta-rifwalet.W , where the fixed part is represented by **beta-rifwallet**). We want to make sure that this release doesn’t affect the other testnet release and viceversa.
E.g.:
If we create a tag v1.0.0-beta.x it must be released to TESTNET only (not RIF Wallet); if we create a tag v1.0.0-beta-rifwallet.x it must be released to RIF Wallet testnet only.

Add CD for rif-wallet-testnet environment

---

.github/workflows/codeql.yml
.github/workflows/deploy.testnet.yml

This PR is to configure the server to automatically deploy in the public testnet environment.  The deployment is triggered when a release is created having a specific a tag format (e.g. vX.Y.Z-beta-testnet.W ). We want to make sure that this release doesn’t affect the other testnet release and viceversa.
E.g.:
If we create a tag v1.0.0-beta-testnet.x it must be released to TESTNET only (not RIF Wallet); if we create a tag v1.0.0-beta-rifwallet.x it must be released to RIF Wallet testnet only.
https://rsklabs.atlassian.net/browse/PP-623

Configure the CD in the Server to deploy to RIF TESTNET environment

---

server-config.rwt.json

-  Remove fee receiver from RWT configuration
- Fee receiver isn't required in RWT

Fix: remove fee receiver from rwt

---

server-config.rwt.json

- Enable SmartWallet and NativeHolderSmartWallet verifiers
- Because both templates need to be usable

PP 745: enable SmartWallet and NativeHolderSmartWallet verifiers

---

server-config.rwt.json

-  Change the verifier configuration to avoid parsing error.
-  The verifiers are parsed as JSON 😓

PP-745: fix rwt configuration

---

package-lock.json
package.json
src/Conversions.ts
src/relayServerUtils.ts
test/unit/relayServerUtils.test.ts

- Implement new getExchangeRate
- Right now RIF Token is supported by both Coinbase and CoinGecko clients, but the first one is selected only, and if it fails, we don’t get the price at all. We should have a strategy that implies the usage of the additional clients if available.
- [PP-755](https://rsklabs.atlassian.net/browse/PP-755)
- https://github.com/rsksmart/rif-relay-client/pull/85

PP-755/pricer-api-selection

---

package-lock.json
package.json
src/RelayServer.ts
src/RelayServer.utils.ts
test/unit/RelayServer.test.ts

- Fix the time logged when the request expiration time is expired or about to expire.
- The minimum acceptable time is wrongly logged.

PP-779: fix expiration date logged on v1

---

package-lock.json
package.json

- Update rif-relay-client to the latest version
- It includes the exchange apis cache.

PP-779: update rif-relay-client package

---

package.json
src/KeyManager.ts
tsconfig.build.json

- create random seed using randomBytes rather than the private key of a random wallet
-  to avoid reduced entropy

fix(RREL-013): improve key creation

---

package-lock.json
package.json
src/commands/Register.ts
src/commands/findWealthyAccount.ts
test/unit/findWealthAccounts.spec.ts

- check that RPC accounts are used on Regtest only
- The wallet installed on the RSK node accessible via RPC is not secure

fix(RREL-17): use rpc accounts for dev purposes only

---

src/KeyManager.ts

-  parse the keys with and without `0x`
-  we don't store the keys with the `0x` prefix any more to be compatible with the v1, but the `ethers.utils.HDNode.fromSeed` isn't able to parse the string without `0x`.

PP-810: fix key parsing

---

package-lock.json
package.json
src/RelayServer.ts
src/ReplenishFunction.ts
src/events/checkReplenish.ts
src/events/index.ts
test/unit/RelayServer.test.ts

- add an event handler to check if the server needs to be replenished
- if an error occurs during the replenishment, the user gets an error and this could be misleading
- RREL-0019

PP-816: do not wait for replenishment when relaying a tx

---

package.json
src/events/checkReplenish.ts
src/events/index.ts

-  avoid pointing to the src folder in the built files
- the built files doesn't have the `src` folder hence they won't be able to run properly

build: avoid pointing to the src folder in the built files

---

config/rwt2.json5

- Allow the RIF Wallet team to use a new environment to test v2 of the server
- Before migrating, they want to perform some tests.

ci: Add the env config for rwt2

---

package-lock.json
package.json

-  Use the latest version of the rif-relay-client
- To support USDRIF

PP-838: update relay client dependency

---

package-lock.json
package.json

-   Change package name to include `@rsksmart`
-  Because when we install it using the github URL, it gets installed as `rif-relay-server` instead of `@rsksmart/rif-relay-server`

PP-830: change package name to include org

---

Readme.md
config/default.json5
src/commands/Register.ts

- update docs
- to clarify keys usage on registration (RREL-0017)
- to clarify that `mnemonic` and `privateKey` are not intended to be used in clear in the json files.

PP-815: update docs to clarify security aspects

---

package-lock.json
package.json
src/TransactionManager.ts
src/TxStoreManager.ts
src/version.ts

- fix parsing of `BigNumber` from local db
- fix `BigNumber` comparison using the `.lt` operator instead of `<`
- `gasPrice` and `gasLimit` were not properly parsed from the database
- `gasPrice` was compared using the `<` operator

PP-842: fix resending underpriced transactions 

---

.github/workflows/deploy.boltz.testnet.yml

-   Implement CD for Boltz Instance running Relay
-   Necessary to execute CD as we have for other relay environments (dev, qa, rwm and rwt)
-   https://rsklabs.atlassian.net/browse/DEVOPS-1891

DEVOPS-1891: Implement CICD for Boltz Testnet

---

src/HttpEnvelopingRequest.ts
src/HttpServer.ts
src/RelayServer.ts
src/definitions/HttpEnvelopingRequest.ts
src/relayServerUtils.ts
test/unit/RelayServer.test.ts
test/unit/relayServerUtils.test.ts

-  do not use the type defined in the client to avoid `PromiseOrValue` type
- redefine the same types in the server without using `PromiseOrValue`.
-  that type is defined from ethers and it may be misleading because when receiving the request from the server, the values will never be promises

fix(RREL-026): avoid using PromiseOrValue type in server
